find_package(PkgConfig QUIET)
pkg_check_modules(PC_WEBRTC_AUDIO_PROCESSING webrtc-audio-processing)

find_path(WEBRTC_AUDIO_PROCESSING_INCLUDE_DIRS webrtc_audio_processing
    HINTS ${PC_WEBRTC_AUDIO_PROCESSING_INCLUDEDIR} ${PC_WEBRTC_AUDIO_PROCESSING_INCLUDE_DIRS}
    PATH_SUFFIXES webrtc_audio_processing)
find_library(WEBRTC_AUDIO_PROCESSING_LIBRARIES webrtc_audio_processing
    HINTS ${PC_WEBRTC_AUDIO_PROCESSING_LIBRARY_DIRS} ${PC_WEBRTC_AUDIO_PROCESSING_LIBDIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(webrtc-audio-processing DEFAULT_MSG
    WEBRTC_AUDIO_PROCESSING_LIBRARIES WEBRTC_AUDIO_PROCESSING_INCLUDE_DIRS)

list(APPEND WEBRTC_AUDIO_PROCESSING_INCLUDE_DIRS ${PC_WEBRTC_AUDIO_PROCESSING_INCLUDE_DIRS})

mark_as_advanced(WEBRTC_AUDIO_PROCESSING_INCLUDE_DIRS WEBRTC_AUDIO_PROCESSING_LIBRARIES)

execute_process(COMMAND ${PKG_CONFIG_EXECUTABLE} webrtc_audio_processing
                OUTPUT_STRIP_TRAILING_WHITESPACE)
